### PR TITLE
[feat] wysiwyg editor [Closes #133]

### LINKED ISSUE #133: Add WYSIWYG to Pages Creation

### PR DESCRIPTION
**Pull request by RRDuke**

### CODE REVIEW

**Comment by codydaig** [comment]
LGTM

**Comment by marcoviappiani** [comment]
can you double check if it's still overriding the style? If so, we should check if there is a way to fix it or if we want to keep it as is

**Comment by RRDuke** [comment]
What I've discovered here is that we aren't 'overriding' anything. Bootstrap provides more default values than angular material. The simplest fix, rather than spending lots of time going through bootstrap and stripping out the offending defaults, would be to set our own styles at some point. Personally, I view this as a lower priority task - I'm ok with the bootstrap defaults for the moment. Thoughts?

**Comment by marcoviappiani** [comment]
LGTM if you're comfortable with it, I'm comfortable with it :) :+1:

**Pull request merged**
