### PR TITLE
[cleanup] Remove Excess Controllers [Closes #220 Closes #219]

### LINKED ISSUE #219: There's no / page by default
Instead the user is redirected to /home

### LINKED ISSUE #220: Remove Excess Controllers
Remove Home and About Controllers from Core Module

### PR DESCRIPTION
**Pull request by codydaig**

### CODE REVIEW

**Comment by RRDuke** [comment]
Does this also address #219?

**Comment by RRDuke** [comment]
Also, please do a search for '$state.go('home') in the repo.

**Comment by codydaig** [comment]
@RRDuke yes

**Comment by codydaig** [comment]
@RRDuke Ready

**Comment by marcoviappiani** [comment]
LGTM

**Pull request merged**
