### PR TITLE
[bug] Ensure slug has preceding '/' upon page creation [Closes #95]

### LINKED ISSUE #95: [bug] shouldn't be able to create a page with a slug that doesn't start with '/'
Currently the client accepts any slug and so does the server. 
This then gets stored but is not accessible with the url.
You can see it's correctly being stored because it appears in the Admin "pages list".

Possible solutions:
- [ x ] client side validation

### PR DESCRIPTION
**Pull request by RRDuke**

### CODE REVIEW

**Comment by trevorhanus** [comment]
:+1:

**Comment by codydaig** [comment]
@RRDuke Can we also add a server side check? Or even more it solely to the server side?

**Comment by RRDuke** [comment]
Would need to be both rather than only server as the front end needs the value right away for the redirect (that I'm working on fixing). Will push up a server-side verification to this pull request shortly

EDIT: I take that back. it immediately performs the database addition and uses the response for further action. Going to switch this to a server check

**Comment by marcoviappiani** [comment]
LGTM

**Pull request merged**
